name: chat_gemini
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.1+4

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  animated_text_kit: ^4.2.2
  auto_route: ^7.8.4
  bloc: ^8.1.3
  clipboard: ^0.1.3
  cloud_firestore: ^4.15.6
  collection: ^1.18.0
  cupertino_icons: ^1.0.6
  equatable: ^2.0.5
  firebase_analytics: ^10.8.10
  firebase_auth: ^4.17.6
  firebase_core: ^2.25.2
  firebase_crashlytics: ^3.4.19
  firebase_storage: ^11.6.7
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  flutter_markdown: ^0.6.20+1
  flutter_signin_button: ^2.0.0 # provides GoogleSignInButton
  freezed_annotation: ^2.4.1
  gap: ^3.0.1
  get_it: ^7.6.7
  google_generative_ai: ^0.2.2
  google_sign_in: ^6.2.1
  google_sign_in_web: ^0.12.3+3
  http: ^1.2.0
  image_picker: ^1.0.7
  injectable: ^2.3.2
  json_annotation: ^4.8.1
  logger: ^2.0.2+1
  rive: ^0.12.4
  share_plus: ^7.2.2

dev_dependencies:
  auto_route_generator: ^7.3.2
  bloc_test: ^9.1.6
  build_runner: ^2.4.8
  fake_cloud_firestore: ^2.4.8
  firebase_auth_mocks: ^0.13.0
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.4.7
  google_sign_in_mocks: ^0.3.0
  injectable_generator: ^2.4.1
  json_serializable: ^6.7.1
  mock_exceptions: ^0.8.2
  mocktail: ^1.0.3
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/

fonts:
  - family: SocialIcons
    fonts:
      - asset: packages/firebase_ui_auth/fonts/SocialIcons.ttf

flutter_icons: flutter_icons_gen.yaml
scripts: scripts.yaml
