name: chat_gemini
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_bloc: ^8.1.4
  bloc: ^8.1.3
  bloc_test: ^9.1.6
  google_generative_ai: ^0.2.2
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  equatable: ^2.0.5
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  logger: ^2.0.2+1
  auto_route: ^7.8.4
  google_sign_in: ^6.2.1
  flutter_signin_button: ^2.0.0 # provides GoogleSignInButton
  gap: ^3.0.1
  cloud_firestore: ^4.14.0
  collection: ^1.18.0
  flutter_markdown: ^0.6.20+1
  share_plus: ^7.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.0
  json_serializable: ^6.7.1
  freezed: ^2.4.7
  build_runner: ^2.4.8
  auto_route_generator: ^7.3.2

flutter:
  uses-material-design: true

  assets:
    - assets/images/

fonts:
  - family: SocialIcons
    fonts:
      - asset: packages/firebase_ui_auth/fonts/SocialIcons.ttf

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/launcher_icon.png"
  adaptive_icon_background: "#00022A"
  adaptive_icon_foreground: "assets/images/launcher_icon.png"
  web:
    generate: true
    image_path: "assets/images/launcher_icon.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/images/launcher_icon.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/images/launcher_icon.png"

flutter_icons: flutter_icons_gen.yaml
scripts: scripts.yaml
